config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    collection do
      get :dashboard
    end
  end

  resources :samples do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :songs do
    collection do
      post :makemix
    end
  end

  resources :song_samples, only: [:create, :destroy]

  root to: "samples#index"
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :user
  has_many :song_samples, dependent: :destroy
  has_many :songs, through: :song_samples
  has_many :comments, dependent: :destroy

  validates :specimen, presence: {message: "You didn't include a file."}
  validates :category, presence: true
  validates :name, presence: true, uniqueness: true
  validates :user, presence: true

  mount_uploader :specimen, SpecimenUploader

  # def self.makesample(sampinfo)
  #   Sample.create(user: User.find(sampinfo['userid']), name: sampinfo['name'], category: sampinfo['category'], remote_specimen_url: sampinfo['url'])
  # end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :authorize_user, except: [:index, :new, :show, :create]

  def index
    @samples = Sample.all
    @topics = Topic.all
    @news = Topic.get_news
  end

  def show
    @sample = Sample.find(params[:id])
    # @comments = Comment.where(sample_id: @sample)
    @comment = Comment.new
  end

  def new
    @sample = Sample.new
  end

  def create
    @sample = Sample.new(sample_params)
    @sample.user = current_user
    @sample.name = @sample.name.gsub(/\s+/, "")

    if @sample.save
      redirect_to samples_path, notice: "Your sample has been accepted."
    else
      flash[:notice] = "Your sample could not be accepted!"
      render "new"
    end
  end

  def destroy
    @sample = Sample.find(params[:id])

    @sample.destroy
    redirect_to samples_path
  end

  private
    def sample_params
      params.require(:sample).permit(:name, :length, :category, :description, :specimen, :remote_specimen_url)
    end

    def authorize_user
      @sample = Sample.find(params[:id])

      unless current_user == @sample.user
        unless user_signed_in? && current_user.admin?
          raise ActionController::RoutingError.new("Not Found")
        end
      end
    end
end

app/views/samples/index.html.erb
<div class="cellblob1">

  <div class="blob">
    <div class="nameblob"><h2>: All Samples :</h2>
      <div class="timestampback">
      </div>
    </div>

  </div>
  <br>
  <br>

  <% @samples.each do |samp| %>
    <div class="blobborder">
      <div class="blob">
        <div class="nameblob"><%= link_to samp.user.name, samp.user %></div> --

          <%= link_to samp do %>
            <span class="indexblob">
             <%= samp.name %>
            </span>
          <% end %>
          <br>
          <div class="timestampback"><h5>[<%= samp.created_at.to_s(:short) %>] -- [<%= samp.category %>]</h5></div>
      </div>
    </div>
    <br>
    <br>

  <% end %>
</div>

<div class="cellblob2">

  <div class="blob">
    <div class="nameblob">
      <h2>: Discussion :</h2>
      <div class="timestampback">
      </div>
    </div>
  </div>

  <br>
  <br>

  <% @topics.each do |topic| %>
    <div class="blob">
      <div class="nameblob"><%= link_to topic.name, topic %> <h6>by <%= link_to topic.user.name, topic.user %></h6>
      </div>

      <span class="indexblob">
        <h6>Alive At:
          <% if topic.comments.first %>
            <%= topic.comments.last.created_at.to_s(:short) %></h6>
          <% else %>
            FRESH</h6>
          <% end %>
      </span>

      <div class="timestampback"></div>
      <div class="disctimestamp"><h6>[ Created: <%= topic.created_at.to_s(:short) %> ]</h6></div>
    </div>
    <br>
    <br>
  <% end %>

  <div class="blob">
    <%= link_to "Add A Topic", new_topic_path %>
  </div>

</div>

<br>
<br>

app/views/samples/new.html.erb
<div class="blob">
  <div class="nameblob"><h1>Stemden :: Add A Sample</h1></div>
</div>
<br>
<br>

<% if current_user %>

<div class="blob">
  <div class="nameblob">
    <h6>(.wav, .mp3, .mp4, .ogg, etc.) -- (.aiff not supported)</h6>
  </div>
</div>

  <%= form_for @sample, html: {multipart: true} do |f| %>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, autofocus: true %><br>
      </div>
    </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :category, "Category" %>
        <%= f.text_field :category %><br>
    </div>
  </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :description, "Description" %>
        <%= f.text_field :description %><br>
    </div>
  </div>

  <div class="blobborderline">
      <div class="blob">
        <%= f.label :length, "Length" %>
        <%= f.text_field :length %><br>
    </div>
  </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :specimen, "Add File" %>
        <%= f.file_field :specimen %>
    </div>
  </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.submit "Submit" %>
      </div>
    </div>


    <div class="blobborderline">
      <div class="blob">
        <% if @sample.errors.full_messages.any? %>
          <% @sample.errors.full_messages.each do |err| %>
            <%= err %>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>

  <% end %>
<% end %>

<br>

<div class="blobborderline">
  <div class="blob">
    <%= link_to "Go Back", samples_path %>
  </div>
</div>

<br>

app/views/samples/show.html.erb
<script type="text/javascript">

  //initialize player + set up controls

  soundManager.setup({
  url: '/swf',
  onready: function() {

    var <%= @sample.name %> = soundManager.createSound({
      id: '<%= @sample.name %>id',
      url: '<%= @sample.specimen_url %>',

      ontimeout: function() {
        // Hrmm, SM2 could not start. Missing SWF? Flash blocked? Show an error, etc.?
        console.log('Soundmanager was unable to start! Fuck!');
      },

      whileplaying: function() {
        $(".timeline").css('width', ((<%= @sample.name %>.position/<%= @sample.name %>.duration) * 100) + '%');
      },

      onstop: function() {
        $(".timeline").css('width', '0%');
      }
    });

      $("#<%= @sample.name %>playbutton").click(function()
        {
          <%= @sample.name %>.play();
        });

      $("#<%= @sample.name %>stopbutton").click(function()
        {
          <%= @sample.name %>.stop();
        });

      $(".timelinecontainer").click(function(e){
        //set song position to % position within timelinediv
          <%= @sample.name %>.setPosition((e.pageX - $(".timelinecontainer").offset().left)/($(".timelinecontainer").width()) * <%= @sample.name %>.duration);
          console.log(e.pageX);
      });
    },
  });
</script>

<div class="blob">
  <div class="nameblob"><h1><%= @sample.name %></h1></div>
</div>

<br>
<br>

<div class="yellowblobborder">
  <a class="blob" href="<%= @sample.specimen_url %>">Download<br>Stem</a>
</div>

<% if @sample.user == current_user %>
  <div class="yellowblobborder">

    <div class="blob"><%= link_to "Delete Stem", sample_path(@sample), method: :delete %></div>
  </div>

<% end %>

<br>
<br>

<div class="playcontrolcontainer">
  <div class="playcontrols">
    <button id="<%= @sample.name %>playbutton"><img src="/img/play.png" alt="Play"></button>
    <button id="<%= @sample.name %>stopbutton"><img src="/img/stop.png" alt="Stop"></button>
  </div>
</div>

<div class="tcwrapper">
  <div class="timelinecontainer">
    <div class="timeline"></div>
  </div>
</div>

<br>
<br>

<% lastuser = "" %>
<% counter = 0 %>

<% @sample.comments.each do |comm| %>
  <% if comm.user.name != lastuser && lastuser != ""  %>
    <br>
    <br>
    <% counter += 1 %>
  <% end %>

  <% if counter % 2 == 0 %>
    <div class="yellowblobborder">
  <% else %>
    <div class="commborder2">
  <% end %>
      <div class="blob">
          <div class="nameblob"><%= comm.user.name %></div><br>
          <%= comm.body %><br>
          <div class="timestampback"><h6><%= comm.created_at.to_s(:short) %></h6>

            <% if comm.user == current_user %>
              <div class="tinyblob"><%= link_to "Delete", sample_comment_path(@sample, comm), method: :delete %></div>
            <% end %>

          </div>
      </div>
      <br>
    </div>



  <% lastuser = comm.user.name %>
<% end %>

<br>
<br>

<div class="blobborder">
  <div class="blob">
    <div class="commform">
    <%= form_for [@sample, @comment] do |f| %>
      <%= f.label :body, "Comment:" %>
      <%= f.text_field :body, autofocus: true %>

      <%= f.submit "Submit" %>

      <% if @comment.errors.full_messages.any? %>
        <% @comment.errors.full_messages.each do |err| %>
          <%= err %>
          <br>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<br>
<br>
<div class="blobborder">
  <div class="blob">
    <%= link_to "Go Back", samples_path %>
  </div>
</div>

<br>
<br>