config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    collection do
      get :dashboard
    end
  end

  resources :samples do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :songs do
    collection do
      post :makemix
    end
  end

  resources :song_samples, only: [:create, :destroy]

  root to: "samples#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :samples
  has_many :songs
  has_many :comments, dependent: :destroy
  has_many :topics, dependent: :destroy

  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "bonsai"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    if current_user && current_user.admin?
      @topic = Topic.new
    end
  end

  def dashboard
    @users = User.all
    @news = Topic.get_news
    @topic = Topic.new
  end

end

app/views/users/dashboard.html.erb
<% @users.each do |user| %>

  <h1><%= user.name %></h1>
  <br>

  <div class="cellblob1">
    <h2>Songs</h2>

    <% user.songs.each do |song| %>
      <%= link_to song.name, song %><h5> by <%= song.user.name %></h5><br>
      <div class="tinyblob admin"><%= link_to "Delete", song_path(song), method: :delete %></div><br>
    <% end %>

  </div>

  <div class="cellblob2">
    <h2>Samples</h2>

    <% user.samples.each do |sample| %>
      <%= link_to sample.name, sample %><h5> by <%= sample.user.name %></h5><br>
      <div class="tinyblob admin"><%= link_to "Delete", sample_path(sample), method: :delete %></div><br>

    <% end %>
  </div>

  <div class="cellblob1">
    <h2>Comments</h2>

    <% user.comments.each do |comment| %>
      <%= comment.body %><h5> by <%= comment.user.name %></h5><br>

      <div class="tinyblob admin">
        <% if comment.topic? %>
          <%= link_to "Delete", topic_comment_path(comment.topic, comment), method: :delete %>
        <% else %>
          <%= link_to "Delete", sample_comment_path(comment.topic, comment), method: :delete %>
        <% end %>

      </div><br>
    <% end %>
  </div>

  <div class="cellblob2">
    <h2>News</h2>

    <% @news.each do |topic| %>
      <%= topic.name %><h5> by <%= topic.user.name %></h5><br>
      <div class="tinyblob admin"><%= link_to "Delete", topic_path(topic), method: :delete %></div><br>
    <% end %>
  </div>

<% end %>

<div class="cellblob1">

  <% if current_user && current_user.admin? %>

    <div class="blob">
      <div class="nameblob">
        <h2>Post News</h2>
      </div>
    </div>

    <br>
    <br>

    <div class="blobborder">
      <div class="blob">
        <div class="commform">
          <%= form_for @topic do |f| %>
            <%= f.label :name, "News:" %>
            <%= f.text_field :name, autofocus: true %>
            <%= f.hidden_field :post_type, value: "news" %>

            <%= f.submit "Submit" %>

            <% if @topic.errors.full_messages.any? %>
              <% @topic.errors.full_messages.each do |err| %>
                <%= err %>
                <br>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="blob">
  <div class="nameblob">
    <h1><%= @user.name %> :: Profile</h1>
  </div>
</div>
<br>
<br>

<div class="cellblob1">

  <div class="blob">
    <div class="nameblob">
      <h2>All Stems</h2>
    </div>
  </div>

  <br>
  <br>

  <div class="blobborder">
    <div class="blob">
        <% @user.samples.each do |samp| %>
          <%= link_to samp.name, samp %> -- <h6><%= samp.created_at.to_s(:short) %></h6><br>
        <% end %>
    </div>
  </div>
  <br>
  <br>

</div>

<div class="cellblob2">

  <div class="blob">
    <div class="nameblob">
      <h2>All Songs</h2>
    </div>
  </div>

  <br>
  <br>

  <div class="blobborder">
    <div class="blob">
        <% @user.songs.each do |song| %>
          <%= link_to song.name, song %> -- <h6><%= song.created_at.to_s(:short) %></h6><br>
        <% end %>
    </div>
  </div>

</div>

<br>
<br>

<div class="cellblob1">

  <div class="blob">
    <div class="nameblob">
      <h2>All Comments</h2>
    </div>
  </div>

  <br>
  <br>

  <div class="blobborder">
    <div class="blob">
        <% @user.comments.order(:created_at).each do |comm| %>
          <div class="nameblob">
            <% if comm.topic? %>
              <%= comm.body %> on: <div class="commborder2"><%= link_to comm.topic.name, comm.topic %></div>
            <% else %>
              <%= comm.body %> on: <div class="yellowblobborder"><%= link_to comm.sample.name, comm.sample %></div>
            <% end %>
          </div> -- <h6><%= comm.created_at.to_s(:short) %></h6><br>
        <% end %>
    </div>
  </div>
<br>
<br>

</div>

<div class="cellblob2">

  <% if current_user && current_user.admin? %>

    <div class="blob">
      <div class="nameblob">
        <h2>Post News</h2>
      </div>
    </div>

    <br>
    <br>

    <div class="blobborder">
      <div class="blob">
        <div class="commform">
          <%= form_for @topic do |f| %>
            <%= f.label :name, "News:" %>
            <%= f.text_field :name, autofocus: true %>

            <%= f.submit "Submit" %>

            <% if @topic.errors.full_messages.any? %>
              <% @topic.errors.full_messages.each do |err| %>
                <%= err %>
                <br>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>
<br>
<div class="blobborder">
  <div class="blob">
    <%= link_to "Go Back", samples_path %>
  </div>
</div>