config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    collection do
      get :dashboard
    end
  end

  resources :samples do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :songs do
    collection do
      post :makemix
    end
  end

  resources :song_samples, only: [:create, :destroy]

  root to: "samples#index"
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :song_samples
  has_many :samples, through: :song_samples
  belongs_to :user

  validates :name, presence: true
  validates :user, presence: true

  def get_urls
    samp_rate = srate ? srate : 44100
    urls = {samps: [], userid: user.id, songid: id, srate: samp_rate}

    song_samples.each do |songsamp|
      urls[:samps] << {link: songsamp.sample.specimen.url.gsub(/\A(\w|\W)*audio\//, ""), gain: songsamp.gain}
    end

    urls
  end

  def self.scrub_fname(filename)
    # Split the name when finding a period which is preceded by some
    # character, and is followed by some character other than a period,
    # if there is no following period that is followed by something
    # other than a period (yeah, confusing, I know)
    fn = filename.split /(?<=.)\.(?=[^.])(?!.*\.[^.])/m

    # We now have one or two parts (depending on whether we could find
    # a suitable period). For each of these parts, replace any unwanted
    # sequence of characters with an underscore
    fn.map! { |s| s.gsub /[^a-z0-9\-]+/i, '_' }

    # Finally, join the parts with a period and return the result
    return fn.join '.'
  end

  def self.mix(logger, songid)
    #last value of songinfo array is output name!
    # second to last is user id of song
    songo = Song.find(songid)
    songname = Song.scrub_fname(songo.name)

    # check for existing filename
    checknames = Sample.where("name LIKE ?", "%#{songname}%").all.to_a
    last = checknames.sort_by! {|s| s.name[-1].to_i }.last

    if last

      logger.info "Found existing sample with #{songname}!"
      iteration = last.name.match(/_\d\z/)

      if iteration
        logger.info "Iteration found"
        songname = "#{songname}_#{(last.name[-1].to_i)+1}"
      else
        logger.info "none found"

        songname = "#{songname}_2"
      end

      logger.info "Name will be #{songname}..."
    end

    songinfo = songo.get_urls
    srate = songinfo[:srate]
    userid = songinfo[:userid]

    filenames_string = ""
    counter = 0

    files = songinfo[:samps]

    files.each do |stemhash|
      # download the boy to the local folder
      stemhash[:filename_noex] = stemhash[:link].match(/\/(.*)\.{1}/)[1]
      stemhash[:filename_ex] = stemhash[:link].match(/\/(.*\z)/)[1]
      `s3cmd get s3://stemden/audio/#{stemhash[:link]} ./process/#{stemhash[:filename_ex]}`
      stemhash[:srate] = `/usr/sox-14.4.2/bin/sox --i -r ./process/#{stemhash[:filename_ex]}`.try(:to_i)

      if stemhash[:srate] != srate
        `/usr/sox-14.4.2/bin/sox ./process/#{stemhash[:filename_ex]} -r #{srate.to_i} ./process/ready-#{stemhash[:filename_ex]}`
      else        
        `/usr/sox-14.4.2/bin/sox ./process/#{stemhash[:filename_ex]} ./process/ready-#{stemhash[:filename_ex]}`
      end

      stemhash[:filename_ex] = "ready-#{stemhash[:filename_ex]}"

      `mv ./process/#{stemhash[:filename_ex]} ./process/#{counter.to_s + stemhash[:filename_ex]}`
      stemhash[:filename_ex] = "#{counter.to_s + stemhash[:filename_ex]}"

      logger.info "This sample right der #{stemhash.inspect}"

      filenames_string += "-v #{stemhash[:gain] || 1} ./process/#{stemhash[:filename_ex]} "
      counter += 1
    end

    # mix them shits
    soxstring = "-m #{filenames_string} ./process/#{songname}.wav"
    logger.info "Mixing #{soxstring}"
    `/usr/sox-14.4.2/bin/sox #{soxstring}`

    # upload them shits
    # `s3cmd put -f --acl-public #{songname}.wav s3://stemden/audio/mixes/#{songname}.wav`

    sampinfo = {name: songname, category: 'mixes', userid: userid, url: "http://s3.amazonaws.com/stemden/audio/mixes/#{songname}.wav"}
    sample = Sample.new(user_id: sampinfo[:userid], name: sampinfo[:name], category: sampinfo[:category])

    uploader = SpecimenUploader.new
    File.open("./process/#{songname}.wav") do |file|
      sample.specimen = file
    end

    
    sample.save
    `rm -rf ./process/*`
    logger.info "Done with #{sample.id}"
    sample
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.user = current_user

    if @song.save

      redirect_to song_path(@song), notice: "Your song has been accepted."
    else
      
      flash[:notice] = "Your song could not be accepted!"
      render 'new'
    end
  end

  def show
    @song = Song.find(params[:id])
    @song_sample = SongSample.new
  end

  def destroy
    @song = Song.find(params[:id])

    @song.destroy
    redirect_to samples_path
  end

  def makemix
    @song = Song.find(params[:id])
    MixMaster.perform_async({type: 'mix', songid: @song.id})
    redirect_to song_path(@song)
  end

  private
    def song_params
      params.require(:song).permit(:name, :user_id, :category, :srate)
    end

    def authorize_user
      unless user_signed_in? && current_user.admin?
        raise ActionController::RoutingError.new("Not Found")
      end
    end
end

app/views/songs/index.html.erb
<div class="blob">
  <div class="nameblob"><h1>Stemden :: All Songs</h1></div>
</div>
<br>
<br>

<% @songs.each do |song| %>
  <div class="blobborder">
    <div class="blob">
      <div class="nameblob"><%= link_to song.user.name, song.user %></div> --

        <%= link_to song do %>
          <span class="indexblob">
           <%= song.name %>
          </span>
        <% end %>
        <br>
        <div class="timestampback"><h5>[<%= song.created_at.to_s(:short) %>] -- [<%= song.category %>]</h5></div>
    </div>
  </div>
  <br>
  <br>
<% end %>

<br>
<br>

<div class="blobborder">
  <div class="blob">
    <%= link_to "Go Back", samples_path %>
  </div>
</div>

app/views/songs/new.html.erb
<div class="blob">
  <div class="nameblob"><h1>Stemden :: Create Song</h1></div>
</div>
<br>
<br>

<% if current_user %>
  <%= form_for @song do |f| %>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, autofocus: true %><br>
      </div>
    </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :category, "Category" %>
        <%= f.text_field :category %><br>
    </div>
  </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :description, "Description" %>
        <%= f.text_field :description %><br>
    </div>

    <div class="blobborderline">
      <div class="blob">
        <%= f.label :srate, "Sample Rate" %>
        <%= f.text_field :srate %><br>
    </div>
  </div>



    <div class="blobborderline">
      <div class="blob">
        <%= f.submit "Submit" %>
      </div>
    </div>


    <div class="blobborderline">
      <div class="blob">
        <% if @song.errors.full_messages.any? %>
          <% @song.errors.full_messages.each do |err| %>
            <%= err %>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>



  <% end %>
<% end %>

<br>

<div class="blobborderline">
  <div class="blob">
    <%= link_to "Go Back", samples_path %>
  </div>
</div>

app/views/songs/show.html.erb
<div class="blob">
  <div class="nameblob">

    <h1>Song :: <span class="indexblob"><%= @song.name %></span></h1>
  </div>
</div>

<br>
<br>
<div class="blobborder">
  <div class="blob">
    <ul class="samples">
      <% @song.song_samples.each do |song_sample| %>
        <div class="nameblob">
          <li>
            <%= link_to "#{song_sample.sample.name}", song_sample.sample %> -- <%= song_sample.convert_gain %> dB -- <%= link_to "#{song_sample.sample.user.name}", song_sample.sample.user %><h5> -- Added By <%= link_to song_sample.user.name, song_sample.user %></h5></li>
            <% if song_sample.user == current_user %>
              <div class="tinyblob"><%= link_to "Delete", song_sample_path(song_sample), method: :delete %></div>
            <% end %>
        </div><br>
      <% end %>
    </ul>
  </div>
</div>

<br>
<br>

<div class="blobborder">
  <div class="blob">
    <div class="nameblob"><h3>Add a Stem</h3></div>
    <%= render partial: 'song_samples/form', locals: { song: @song } %>
  </div>
</div>

<br>
<br>

<%= button_to "Mix", {controller: :songs, action: :makemix, id: @song.id}, method: :post %>

<br>
<br>

<div class="blobborder">
  <div class="blob">
    <%= link_to "Go Back", songs_path %>
  </div>
</div>
<br>
<br>